### ISSUE TITLE
'ARTTSTrainer' object has no attribute 'load_trained_modules'

### ISSUE THREAD

**Issue by EthanLifeGreat** [unilight/seq2seq-vc#17]
Hi, I'm doing TTS-pretrained VC model training.

When excuting this command
```
cd egs/ljspeech/tts1
CUDA_VISIBLE_DEVICES=1 ./run.sh --tts_aept_checkpoint exp/char_tacotron_en_1124/checkpoint-60000steps.pkl --stage 6 --stop_stage 6 --tag en_1124
```

The following error occured:
```
Traceback (most recent call last):
  File "......./seq2seq_vc/bin/vc_train.py", line 487, in <module>
    main()
  File "...../seq2seq_vc/bin/vc_train.py", line 460, in main
    trainer.load_trained_modules(
AttributeError: 'ARTTSTrainer' object has no attribute 'load_trained_modules'
```

It seems that the function 'load_trained_modules' was not implemented in ARTTSTrainer nor in any other classes in the project. I see a method with the same name in espnet: espnet/asr/pytorch_backend/asr_init.py, but the input arguments do not match the ones used in this project.

I'm working on myself to solve this issuse by imitating the espnet function. 

But still an early reply is desperated needed.

**Comment by unilight** [comment]
Hi @EthanLifeGreat, thank you for trying the recipe!

While I haven't actually run the script for a long time (since it was implemented quite a while ago), I am rather curious why `ARTTSTrainer` is used in the AEPT stage. IIRC it should be using `ARVCTrainer`. Can you check `train.log` and see which trainer is being used? If the `ARTTSTrainer` is used, can you try to add the following line to the `conf/tts_aept.yml` file, and see it it makes the program use `ARVCTrainer`?

```
trainer_type: ARVCTrainer
```

Either way, it is a problem to be fixed. This repo has gone a long way, especially recently I don't quite use AR models anymore, as I shift to using non-AR models due to their robustness. As a result, some old scripts might not be working due to code library changes. I'm eternally grateful that you caught this!

**Comment by EthanLifeGreat** [comment]
> Hi @EthanLifeGreat, thank you for trying the recipe!
> 
> While I haven't actually run the script for a long time (since it was implemented quite a while ago), I am rather curious why `ARTTSTrainer` is used in the AEPT stage. IIRC it should be using `ARVCTrainer`. Can you check `train.log` and see which trainer is being used? If the `ARTTSTrainer` is used, can you try to add the following line to the `conf/tts_aept.yml` file, and see it it makes the program use `ARVCTrainer`?
> 
> ```
> trainer_type: ARVCTrainer
> ```
> 
> Either way, it is a problem to be fixed. This repo has gone a long way, especially recently I don't quite use AR models anymore, as I shift to using non-AR models due to their robustness. As a result, some old scripts might not be working due to code library changes. I'm eternally grateful that you caught this!


Great! By adding these 2 lines to `conf/tts_aept.yml`, the TTS autoencoder pretraining started successfully.
``` 
trainer_type: ARVCTrainer
collater_type: ARVCCollater
```

Thank you for your valuable reply. I'm colsing this issue.

**Comment by unilight** [comment]
@EthanLifeGreat Glad to hear that! You are more than welcomed to open a PR on this fix :)
